#!/usr/bin/env python3

import time
import os.path, sys
import configparser as cp
# -- system --
from ai_core.aiBot import aiBot
from sys_core.rxtxRouter import rxtxRouter


# -- process input args --
if len(sys.argv) == 1:
   sys.argv.append("run.ini")

if len(sys.argv) != 2:
   print("BadCountIncomingArgs")
   exit(1)

# -- -- -- --
THIS_FILE, INI_FILE = sys.argv
hdr: str = "--- loading ---"
print(f"\n{hdr}\n[ main: {THIS_FILE} ]\n[ ini: {INI_FILE} ]\n[ cwd: {os.getcwd()} ]\n")

ini_path = f"conf/{INI_FILE}"
if not os.path.exists(ini_path):
   print(f"PathNotFound: {ini_path}")
   exit(1)

# -- ini load --
FILES_TO_LOAD_CNT: int = 1
INI_OBJ: cp.ConfigParser = cp.ConfigParser()
tmp = INI_OBJ.read(ini_path)
if len(tmp) != FILES_TO_LOAD_CNT:
   print(f"BadIniLoad: {len(tmp)}")
   exit(1)


# todo: later
# -- create rf-tx in/pilot --

# -- create rf-tx out/fc --


# -- create ai bot --
AI_BOT: aiBot = aiBot(ini=INI_OBJ)
AI_BOT.init()
AI_BOT.start()

# -- create rxtx router --
RXTX_ROUTER: rxtxRouter = rxtxRouter(aibot=AI_BOT, ini=INI_OBJ)
RXTX_ROUTER.load_ini()
RXTX_ROUTER.start()


# -- -- -- main loop -- -- --
def main():
   print("-- [ main ] --")
   while True:
      print("-- main --")
      time.sleep(4.0)


# -- -- -- entry point -- -- --
if __name__ == "__main__":
   main()
