#!/usr/bin/env python3

import os.path
import sys, configparser as cp


# -- load start args
this_file = None; ini_file = None
try:
   if len(sys.argv) != 2:
      print("BadCountIncomingArgs")
      exit(1)
   # -- -- -- --
   this_file, ini_file = sys.argv
except ValueError as ve:
   ini_file = "run.ini"
finally:
   pass

print(f"\n[ running: {this_file} ]\n[ ini: {ini_file} ]\n[ cwd: {os.getcwd()} ]")

if os.path.exists(ini_file):
   pass


def main():
   print("-- [ main ] --")


# -- -- entry point -- --
if __name__ == "__main__":
   main()
