#!/usr/bin/env python3

import os.path
import sys, configparser as cp


# -- load start args
this_file, ini_file = sys.argv
print(f"\n[ running: {this_file} ]\n[ ini: {ini_file} ]\n[ cwd: {os.getcwd()} ]")

if os.path.exists(ini_file):
   pass


def main():
   print("-- [ main ] --")


# -- -- entry point -- --
if __name__ == "__main__":
   main()
