#!/usr/bin/env python3

import cv2, time
from picamera2 import Picamera2, MappedArray, Preview


colour = (0, 255, 0)
origin = (30, 30)
rec_pnt0 = 90, 90
rec_pnt1 = 200, 200
rec_color = (0, 0, 255)
font = cv2.FONT_HERSHEY_SIMPLEX
scale = 0.8
thickness = 2


def apply_timestamp(request):
   timestamp = time.strftime("%Y/%m/%d %X")
   with MappedArray(request, "main") as m:
      cv2.putText(m.array, timestamp, origin, font, scale, colour, thickness)
      cv2.rectangle(m.array, rec_pnt0, rec_pnt1, rec_color, thickness)
      picam2.pre_callback = apply_timestamp


picam2 = Picamera2()
picam2.pre_callback = apply_timestamp
camera_config = picam2.create_preview_configuration({"size": (640,480)})
picam2.configure(camera_config)
picam2.start_preview(Preview.DRM)
picam2.start(show_preview=True)


while True:
   print("Preview.DRM")
   time.sleep(4.0)
