#!/usr/bin/env python3

import time, numpy as np
from picamera2 import Picamera2, Preview


picam2 = Picamera2()
camera_config = picam2.create_preview_configuration()
picam2.configure(camera_config)
picam2.start_preview(Preview.DRM)
picam2.start()
time.sleep(1.0)

overlay = np.zeros((300, 400, 4), dtype=np.uint8)
overlay[:150, 200:] = (255, 0, 0, 64)
overlay[150:, :200] = (0, 255, 0, 64)
overlay[150:, 200:] = (0, 0, 255, 64)
picam2.set_overlay(overlay)

while True:
   print("Preview.DRM")
   time.sleep(4.0)
