#!/usr/bin/env python3

import sys, time
# -- core --
from core.radioSim import radioSim


# -- default port --
DEV: str = "/dev/ttyUSB1"

# -- load args --
if len(sys.argv) > 1:
   devstr: str = str(sys.argv[1])
   if "/dev/tty" in devstr:
      DEV = devstr
   else:
      pass
# -- end load --


# 9600, 14400, 19200, 38400, 57600, 115200
BAUD: int = 115200
SLEEP_SEC: float = 1.0


RADIO_SIM: radioSim = radioSim(dev=DEV, baud=BAUD)
RADIO_SIM.init()
RADIO_SIM.start()


def __main_loop_tick():
   try:
      print("[ __main_loop_tick ]")
   except Exception as e:
      print(e)
   finally:
      pass


# -- -- [ main loop ticks ] -- --
while True:
   __main_loop_tick()
   time.sleep(SLEEP_SEC)
